export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const DRAG_HAPPENED_IN_OTHER_LIST = "DRAG_HAPPENED_IN_OTHER_LIST";
export const DRAG_HAPPENED_IN_SAME_LIST = "DRAG_HAPPENED_IN_SAME_LIST";